name: ecommerce
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  hive: ^2.2.3
  provider: ^6.1.2
  go_router: ^14.6.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  injectable: ^2.5.0
  flutter_svg: ^2.0.16
  pinput: ^5.0.0
  dio: ^5.7.0
  dartz: ^0.10.1
  get_it: ^8.0.3
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^9.2.2
  cached_network_image: ^3.4.1
  another_flushbar: ^1.12.30
  smart_auth: ^2.0.0
  dropdown_search: ^6.0.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter_dotenv: ^5.2.1
  intl: ^0.19.0
  flutter_native_splash: ^2.4.3
  url_launcher: ^6.3.1
  jwt_decoder: ^2.0.1
  device_preview: ^1.2.0
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.0
  flutter_spinkit: ^5.2.1
  razorpay_flutter: ^1.3.7
  hive_flutter: ^1.1.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.0.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env

